import Head from "next/head";
import Image from "next/image";
import React, { useState, useEffect } from "react";
import axios from "axios";
import HomeScreen from "../components/HomeSreen";
export default function Home({ data }) {
  // const [posts, setPosts] = useState([]);

  // const fetchData = async () => {
  //   const { data } = await axios.get(API_URL);
  //   setPosts(data);
  // };

  // useEffect(() => {
  //   fetchData();
  // }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <HomeScreen data={data} />
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch("https://fakestoreapi.com/products");
  const data = await res.json();
  // console.log(data);

  // Pass data to the page via props
  return { props: { data } };
}
